# Indexer-specific settings for Local environment

global:
  environment: local
  namespace: kt-datahaven-local

image:
  tag: local
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: datahaven-dockerhub

ingress:
  enabled: false

node:
  chain: local
  customChainspecUrl:
  forceDownloadChainspec: false
  chainData:
    storageClass: "hostpath"
    persistence:
      size: 10Gi
  chainKeystore:
    storageClass: "hostpath"
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "200m"
