name: dh-beacon-relay
description: Datahaven Beacon Relay
fullnameOverride: dh-beacon-relay

image:
  repository: moonsonglabs/snowbridge-relayer
  pullPolicy: Always
  tag: latest

imagePullSecrets:
  - name: datahaven-dockerhub

config:
  name: "beacon-relay"

existingSecretName: "dh-beacon-relay-sub-key"

extraArgs: [
  "run",
  "beacon",
  "--config",
  "/configs/beacon-relay.json",
  "--substrate.private-key-file",
  "/secrets/dh-beacon-relay-sub-key",
]
