name: dh-execution-relay
description: Datahaven Execution Relay
fullnameOverride: dh-execution-relay

image:
  repository: moonsonglabs/snowbridge-relay
  pullPolicy: Always
  tag: latest

imagePullSecrets:
  - name: datahaven-dockerhub

config:
  name: "execution-relay"

existingSecretName: "dh-execution-relay-substrate-key"

relayData:
  storagePath: "/relay-data"
  storageClass: "gp2"
  volumeSize: 10Gi

extraArgs: [
  "run",
  "execution",
  "--config",
  "/configs/execution-relay.json",
  "--substrate.private-key-file",
  "/secrets/dh-execution-relay-substrate-key",
]
